### ISSUE TITLE
subscription

### ISSUE THREAD

**Issue by farzam-parto** [jeweltheme/kite-coming-soon-template#2]
Hi,
tnx for this beautiful template,
can you please tell me how can I connect the mailchimp to subscribe.php?

**Comment by jeweltheme** [comment]
Hi,
Regarding this issue and License. We will give an update on next week.
Thanks

**Comment by jeweltheme** [comment]
Hi,
Go to http://mailchimp.com they will give you a api key for your subscriber lists. Place it on subscribe.php file. 
That's it.
Thanks
