### ISSUE TITLE
count down

### ISSUE THREAD

**Issue by robjimenez30** [jeweltheme/kite-coming-soon-template#4]
The count down for html template is not counting down to 0. It goes back to the set value. Please help.

**Comment by jeweltheme** [comment]
Thanks for informing. We will solve this issue on HTML Version. 
You can check WordPress Version also: http://jeweltheme.com/product/kite-coming-soon-wordpress-plugin/

Thanks

**Comment by robjimenez30** [comment]
I need this one working before i decided to buy anything please

**Comment by jeweltheme** [comment]
We've solved this issue in the WordPress Version. You can take a look "Kite Coming Soon WordPress Plugin" Demo.
http://jeweltheme.com/product/kite-coming-soon-wordpress-plugin/

Thanks
