### ISSUE TITLE
Email form doesn't send email

### ISSUE THREAD

**Issue by wileybob** [jeweltheme/kite-coming-soon-template#5]
not sure what im doing wrong, i am a newbie, but i changed the email address to mine in both the email.php and the contact.php, nothing sends. i can get other php forms to work, but not this one

**Comment by stylobaidu** [comment]
how do i modify the count down time?

**Comment by ferminmg** [comment]
@stylobaidu  just change the targetDate at functions.js

`targetDate: {
             'day': 13,
             'month': 10,
             'year': 2018,
             'hour': 9,
             'min': 0,
             'sec': 0
         },`
